version: "2"
services:
  postgres:
    image: "postgres"
    volumes:
      - ./postgres-data:/data
    environment:
      POSTGRES_USER: "example_api"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "example_api"
  etcd:
    depends_on:
      - postgres
    image: "elcolio/etcd"
    volumes:
      - ./etcd-data:/data
  example-api:
    depends_on:
      - etcd
      - postgres
    links:
      - etcd
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile-compose
    image: example-api:latest
    container_name: example-api
    ports:
      - "8080:8080"
    environment:
      ETCD_ENDPOINTS: "http://etcd:2379"
    command: [example-api, runserver]
